### ISSUE TITLE
perform on png

### ISSUE THREAD

**Issue by nathanb2** [akshaychandra21/Alphabet_Recognition_RealTime#1]
@akshaychandra21 please can you explain how can i perform the prediction from png (hand write text in png image).
Thank's for your great code!!!

**Comment by nathanb2** [comment]
@akshaychandra21 when i run alphabet_recognition.py it's give error:
UnboundLocalError: local variable 'name' referenced before assignment

**Comment by acl21** [comment]
This piece of code should help you predict for png images. 

```
# Load the image and convert it to grayscale
img = cv2.imread('file-name.png')
img = cv2.cvtColor(blackboard, cv2.COLOR_BGR2GRAY)

# Resize the image to model input dimension
img = cv2.resize(img, (28, 28))

# Convert img to a numpy array
img = np.array(img)

# Preprocess the image (similar preprocessing was performed before training)
img = img.astype('float32')/255

# Predict using the models
prediction1 = mlp_model.predict(img.reshape(1,28,28))[0]
prediction1 = np.argmax(prediction1)
prediction2 = cnn_model.predict(img.reshape(1,28,28,1))[0]
prediction2 = np.argmax(prediction2)
```

**Comment by acl21** [comment]
> when i run alphabet_recognition.py it's give error:
> UnboundLocalError: local variable 'name' referenced before assignment

But there is no variable 'name' in the alphabet_recognition.py file. Can you specify the line number at which you are getting this error?

**Comment by nathanb2** [comment]
@akshaychandra21 Traceback (most recent call last):
  File "C:/Users/nathanb/Downloads/Alphabet_Recognition_RealTime-master/alphabet_recognition.py", line 7, in <module>
    mlp_model = load_model('emnist_mlp_model.h5')
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 419, in load_model
    model = _deserialize_model(f, custom_objects, compile)
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 225, in _deserialize_model
    model = model_from_config(model_config, custom_objects=custom_objects)
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\saving.py", line 458, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\layers\__init__.py", line 55, in deserialize
    printable_module_name='layer')
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\utils\generic_utils.py", line 145, in deserialize_keras_object
    list(custom_objects.items())))
  File "C:\Users\nathanb\AppData\Local\Programs\Python\Python36\lib\site-packages\keras\engine\sequential.py", line 294, in from_config
    model = cls(name=name)
UnboundLocalError: local variable 'name' referenced before assignment

i got the same error in cnn_model_builder.py but after uncomment this code:
"""
# Train the model
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))

# Save the model weights for future reference
model.save('emnist_cnn_model.h5')
"""
this file run

**Comment by acl21** [comment]
Is the emnist_mlp_model.h5 present in your project directory?

**Comment by nathanb2** [comment]
@akshaychandra21 yes in line 290 in alphabet_recognition.py in get:

<class 'list'>: [{'class_name': 'Flatten', 'config': {'name': 'flatten_2', 'trainable': True, 'batch_input_shape': [None, 28, 28], 'dtype': 'float32'}}, {'class_name': 'Dense', 'config': {'name': 'dense_4', 'trainable': True, 'units': 512, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'VarianceScaling', 'config': {'scale': 1.0, 'mode': 'fan_avg', 'distribution': 'uniform', 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}}, {'class_name': 'Dropout', 'config': {'name': 'dropout_3', 'trainable': True, 'rate': 0.2, 'noise_shape': None, 'seed': None}}, {'class_name': 'Dense', 'config': {'name': 'dense_5', 'trainable': True, 'units': 512, 'activation': 'relu', 'use_bias': True, 'kernel_initializer': {'class_name': 'VarianceScaling', 'config': {'scale': 1.0, 'mode': 'fan_avg', 'distribution': 'uniform', 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}}, {'class_name': 'Dropout', 'config': {'name': 'dropout_4', 'trainable': True, 'rate': 0.2, 'noise_shape': None, 'seed': None}}, {'class_name': 'Dense', 'config': {'name': 'dense_6', 'trainable': True, 'units': 26, 'activation': 'softmax', 'use_bias': True, 'kernel_initializer': {'class_name': 'VarianceScaling', 'config': {'scale': 1.0, 'mode': 'fan_avg', 'distribution': 'uniform', 'seed': None}}, 'bias_initializer': {'class_name': 'Zeros', 'config': {}}, 'kernel_regularizer': None, 'bias_regularizer': None, 'activity_regularizer': None, 'kernel_constraint': None, 'bias_constraint': None}}]

**Comment by acl21** [comment]
I think this is a Keras issue. Is Keras 2.1.4 installed on your machine?

**Comment by nathanb2** [comment]
@akshaychandra21 no it's 2.2.3

**Comment by acl21** [comment]
Can you try downgrading keras and run the code again?

**Comment by nathanb2** [comment]
@akshaychandra21 work thank's!
do you think that i will can run this code on raspberryPi 3?

**Comment by acl21** [comment]
@nathanb2 I have never worked with raspberry pies. Cannot answer your question. Are you talking about raspberry pi's computational limitations?

**Comment by nathanb2** [comment]
@akshaychandra21 not precisely but it's sure one of the problems but I hope that it's will work (i can do only the final predict step on the raspberry), I thank more for the library because I had many problems with the libraries on the raspberry.
Thank you very much!

**Comment by acl21** [comment]
Glad I could help you with it. I am closing the issue.
