### ISSUE TITLE
Getting error on mnist

### ISSUE THREAD

**Issue by karki53** [akshaychandra21/Alphabet_Recognition_RealTime#2]
Import errror cannot inport MNIST firm mnist

**Comment by karki53** [comment]
Sir evrything wkrking fine... But nothing is being pridicted by the camra...  Please help mee sir

**Comment by acl21** [comment]
The default setting can find blue/dark-blue coloured objects in the picture. Which object are you using to draw the alphabet?

**Comment by saleem-hadad** [comment]
Hi @karki53 
did you manage to solve the error above and how?
Thanks in advance 👍
